version: '3.8'

x-name: supabase

services:
  studio:
    # Existing studio service configuration

  kong:
    # Existing kong service configuration

  realtime:
    # Existing realtime service configuration

  db:
    # Existing db service configuration

  vector:
    # Existing vector service configuration

  supavisor:
    # Existing supavisor service configuration

  analytics:
    # Existing analytics service configuration

  n8n:
    container_name: supabase-n8n
    image: n8nio/n8n:0.211.2
    restart: unless-stopped
    ports:
      - 5678:5678
    environment:
      N8N_BASIC_AUTH_USER: admin
      N8N_BASIC_AUTH_PASSWORD: changeme
      N8N_EDITOR_BASE_URL: http://localhost:5678
      N8N_WEBHOOK_TUNNEL_URL: http://localhost:5678
      N8N_PROTOCOL: http
      N8N_HOST: 0.0.0.0
      N8N_PORT: 5678
      N8N_PUSH_REFRESH_INTERVAL: 2000
      N8N_EXECUTIONS_DATA_DIR: /home/node/n8n/executions
    volumes:
      - n8n-data:/home/node/n8n

volumes:
  n8n-data:
    driver: local
