site_name: Supagrok Documentation
site_description: Documentation for Supagrok components
site_author: swipswaps
repo_url: https://github.com/swipswaps/supagrok
edit_uri: edit/main/docs/

theme:
  name: material
  palette:
    primary: indigo
    accent: indigo
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  icon:
    repo: fontawesome/brands/github

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - tables
  - footnotes
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

nav:
  - Home: index.md
  - rEFInd Configuration:
    - Overview: refind_config.md
  - Gaze Tracking:
    - Overview: gaze_tracking.md
  - Testing:
    - Overview: testing.md

plugins:
  - search
  - minify:
      minify_html: true
